# Generated by Django 4.2.4 on 2023-09-18 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="isbn",
            field=models.CharField(
                default=0, max_length=20, verbose_name="field for isbn num"
            ),
            preserve_default=False,
        ),
    ]
